cmake_minimum_required(VERSION 2.8.2)

include(${CTEST_SCRIPT_DIRECTORY}/CMakeDashboardScriptUtils.cmake)

#
# Dashboard properties
#
set(HOSTNAME              "factory")
set(CTEST_DASHBOARD_ROOT  "$ENV{HOME}/Dashboards/Nightly/")

#
# Dashboard options
#
set(WITH_KWSTYLE FALSE)
set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
set(WITH_DOCUMENTATION FALSE)
#set(DOCUMENTATION_ARCHIVES_OUTPUT_DIRECTORY ) # for example: $ENV{HOME}/Projects/Doxygen
set(WITH_PACKAGES TRUE)
set(CTEST_BUILD_CONFIGURATION "Release")

set(CTEST_INCLUDED_SCRIPT_NAME ${HOSTNAME}_CTKAppLauncher_common.cmake)
include(${CTEST_SCRIPT_DIRECTORY}/${CTEST_INCLUDED_SCRIPT_NAME})

#
# Dashboard type
#
set(SCRIPT_MODE "nightly") # "experimental", "continuous", "nightly"

#
# Additionnal CMakeCache options
#
set(ADDITIONNAL_CMAKECACHE_OPTION "
")

#
# Project specific properties
#
set(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/CTKAppLauncher")
set(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/CTKAppLauncher-build-0")

# List of test that should be explicitly disabled on this machine
set(TEST_TO_EXCLUDE_REGEX "")

# set any extra environment variables here
if(UNIX)
  set(ENV{DISPLAY} ":0")
endif()


##########################################
# WARNING: DO NOT EDIT BEYOND THIS POINT #
##########################################

set(CTEST_NOTES_FILES "${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}")

#
# Project specific properties
#
set(CTEST_PROJECT_NAME "CTKAppLauncher")
set(CTEST_BUILD_NAME "${MY_OPERATING_SYSTEM}-${MY_COMPILER}-${MY_BITNESS}bits-QT${MY_QT_VERSION}-${CTEST_BUILD_CONFIGURATION}")

file(WRITE "${CTEST_DASHBOARD_ROOT}/CTKAppLauncher-build-0 - CTKAppLauncher-build-${CTEST_BUILD_NAME}-${SCRIPT_MODE}.txt" "Generated by ${CTEST_SCRIPT_NAME}")

#
# Display build info
#
message("site name: ${CTEST_SITE}")
message("build name: ${CTEST_BUILD_NAME}")
message("script mode: ${SCRIPT_MODE}")
message("coverage: ${WITH_COVERAGE}, memcheck: ${WITH_MEMCHECK}")

#
# Convenient function allowing to download a file
#
function(download_file url dest)
  file(DOWNLOAD ${url} ${dest} STATUS status)
  list(GET status 0 error_code)
  list(GET status 1 error_msg)
  if(error_code)
    message(FATAL_ERROR "error: Failed to download ${url} - ${error_msg}")
  endif()
endfunction()

#
# Download and include dashboard driver script
#
set(url http://www.commontk.org/images/6/6c/CtkAppLauncherDashboardDriverScript.cmake.txt)
set(dest ${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}.driver)
download_file(${url} ${dest})
include(${dest})
